apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: penkowebappregistry.azurecr.io/web-app-penko:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
spec:
  selector:
    app: fastapi-app
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: LoadBalancer
