ame: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: penkowebappregistry.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: penkowebappregistry.azurecr.io/web-app-penko:${{ github.sha }}

  deploy_to_aks:
  needs: build_and_push_docker_image
  runs-on: ubuntu-latest
  steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Install and configure Azure CLI
    run: |
      sudo apt-get update
      sudo apt-get install -y azure-cli
      az version
      echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
      az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

  - name: Get AKS Credentials
    run: |
      az aks get-credentials --name webAppAKSCluster --resource-group RG-Final-Project

  - name: Deploy to AKS
    run: |
      kubectl kustomize k8s | envsubst | kubectl apply -f -
