name: Production Workflow

on:
  push:
    branches:
      - production

jobs:
  build_and_test:
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

